### PR TITLE
Update to ungoogled-chromium 123.0.6312.58

### LINKED ISSUE #151: Use arm64 LLVM when building UGC on Apple Silicon
(This can still be viewed as a part of the works to improve compiling efficiency)

As for now, even if we build ungoogled-chromium-macos on Apple Silicon (arm64), an x86-64 version of LLVM is still used to compile. I think we should try to use arm64 LLVM in this case instead, so no translation for binaries are needed.

This might consist of appending different entries to `downloads.ini` while running build script.

Any opinions on this? /cc @networkException @PF4Public

### PR DESCRIPTION
**Pull request by Cubik65536**
Notes:

- LLVM is updated to 18. (continuation of #155)
	- closes #151 (P.S.: The use of ARM64 LLVM improved build time on local environment by a lot.)
	- LLVM 17 related patches is removed.
- A submodule bump is made.
- A patch refresh is made.
- Rust disable patches are removed.
- Rust toolchain download and unpack are added.
- Rust is enabled.
- `disable-missing-clang-flags` patch is removed.
- Documentations related to ungoogled-chromium update is updated.

---

Builds and runs fine locally.

image

### CODE REVIEW

**Comment by Cubik65536** [comment]
I got the following error:

``` sh
+ ninja -C out/Default chrome chromedriver
ninja: Entering directory `out/Default'
ninja: error: '../../third_party/llvm-build/Release+Asserts/lib/clang/19/lib/darwin/libclang_rt.osx.a', needed by 'obj/third_party/protobuf/libprotoc_lib.a', missing and no known rule to make it
```

It requires `clang/19` but the included clang with LLVM is `clang/18`...

I couldn't find any way to fix this... Any idea how this can be fixed?

**Comment by arjpar** [comment]
The latest LLVM (18) version uses clang 18. Clang 19 (master/git) is still in development as is LLVM 19 (master/git). If you need to build with Clang 19, the LLVM version needs to bump but it won't be as stable. Does macOS require a higher clang/LLVM version than other platforms? I wonder why, it doesn't make sense to me why it would.

**Comment by Cubik65536** [comment]
> The latest LLVM (18) version uses clang 18. Clang 19 (master/git) is still in development as is LLVM 19 (master/git). If you need to build with Clang 19, the LLVM version needs to bump but it won't be as stable. Does macOS require a higher clang/LLVM version than other platforms? I wonder why, it doesn't make sense to me why it would.

I am aware that version 19 is in git master, but I'd strongly prefer to use the released version instead of the git in development version.

I don't know why Chromium itself needs a higher instable version (in history, some platforms, like macOS and Windows, UGC requires a patch to revert clang requirement from 18 to 17, when clang 18 is not released yet), and as far as I can tell, the Windows version of ungoogled-chromium doesn't have a patch to "fix" the clang 19 requirement for version 123.

I'm still trying to find a way to change the requirement setting.

**Comment by arjpar** [comment]
> I'd strongly prefer to use the released version instead of the git in development version
I agree.

> Windows version of ungoogled-chromium doesn't have a patch to "fix" the clang 19 requirement for version 123
What about Linux?

**Comment by Cubik65536** [comment]
> What about Linux?

I don't see a patch for `protablelinux`, and other versions aren't updated recently.

I am not familiar with how `protablelinux` patches works though, so I might have missed something.

**Comment by Cubik65536** [comment]
> I got the following error:
> 
> ```shell
> + ninja -C out/Default chrome chromedriver
> ninja: Entering directory `out/Default'
> ninja: error: '../../third_party/llvm-build/Release+Asserts/lib/clang/19/lib/darwin/libclang_rt.osx.a', needed by 'obj/third_party/protobuf/libprotoc_lib.a', missing and no known rule to make it
> ```
> 
> It requires `clang/19` but the included clang with LLVM is `clang/18`...
> 
> I couldn't find any way to fix this... Any idea how this can be fixed?

This is now fixed.

**Comment by Cubik65536** [comment]
This version is now ready!

**Comment by Cubik65536** [comment]
Still waiting for review here 😢
/cc @PF4Public @networkException

**Pull request closed without merging**
