### PR TITLE
Update to ungoogled-chromium 119.0.6045.159

### PR DESCRIPTION
**Pull request by Cubik65536**
Notes:
- A submodule bump is made.
- Some patches were refreshed.
	- Two patches were removed as the targeted code from Chromium were removed. (P.S.: This is the first time for me to make these kind of changes, if I made something wrong, please point it out.)

------

Builds and runs fine locally.

image

### CODE REVIEW

**Review by PF4Public — APPROVED** [review]
Looking good

**Comment by PF4Public** [comment]
Thanks @Cubik65536 , sorry for the delay.

**Comment by Cubik65536** [comment]
@networkException sorry for the ping, but it seems that the ci are all finished (even for the tags) but no release is created and no `dmg` uploaded?

**Comment by networkException** [comment]
The build failed, ill look at this in a few hours

**Comment by benhaney** [comment]
There's two issues that I'm seeing right now. One is causing an error half way through the build on any platform, and the other is stopping the arm build from ever really getting started.

The first issue is caused by https://github.com/chromium/chromium/commit/11065a962f6a15212ac1b021d19a0072c62108bc, which introduces the use of a symbol only available in the macOS 14 SDK, provided by Xcode 15. Fixing this should be as simple as updating your actions workflow to select Xcode 15.0.1 instead of 14.3.1

The second issue is caused by python 3.12 dropping the deprecated distutils, which provided the `pkg_resources` module that a Chromium build script used for arm builds. Github Actions macOS runners already updated to python 3.12, but the upstream Chromium fix for this (https://github.com/chromium/chromium/commit/da3f836905f6926533edd37495b238a9155e1984) is part of the 120 sources. I think the easiest thing to do here would be to temporarily backport that commit as an extra patch, unless you know a good way to make `pkg_resources` available again to the build environment.

Hopefully saves y'all some debugging efforts.

**Comment by PF4Public** [comment]
@Cubik65536 Would you be able to fix this according to @benhaney suggestions?

**Comment by Cubik65536** [comment]
> @Cubik65536 Would you be able to fix this according to @benhaney suggestions?

I’ll take a look at it this weekend.

**Pull request merged**
