### PR TITLE
ci: Use macOS 15 to build

### PR DESCRIPTION
**Pull request by Cubik65536**
Chromium changed a lot of things since version 131 to take advantage of macOS 15 SDK, like [[5894764]](https://chromium-review.googlesource.com/c/chromium/src/+/5894764/3/ui/events/keycodes/keyboard_code_conversion_mac.mm) (also see https://github.com/ungoogled-software/ungoogled-chromium/pull/3089#issuecomment-2480123156) and [[5868514]](https://chromium-review.googlesource.com/c/chromium/src/+/5868514/10/ui/base/cocoa/cursor_utils.mm) (also see https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/11963693332).

As a consequence, our GitHub Action Host, running macOS 13 (for Intel) and 14 (for ARM), aren't able to build new versions. As it might be too much of hassle to revert all changes, and I actually expect more changes to come, I decided to move to macOS 15 Action Runner for both platforms.

Potential downsides are:

- `macos-15` runner is in public preview state for GitHub Action, so it might be unstable;
- compatibility with older macOS version might not be as great;
- as there's no Intel runner with macOS 13+, we have to cross compile x64 ungoogled-chromium from ARM hosts, which might make the now ages long building action even longer (or shorter, we shall see, ARM might be still faster).

But this is the best solution I can come up with for now.

Current Test Run: https://github.com/iXORTech/ungoogled-chromium-macos/actions/runs/11984866059 (the 7th one, let's hope it pass)

Signed-off-by: Qian Qian "Cubik"‎ <<cubik65536@cubik65536.top>>

### CODE REVIEW

**Comment by Cubik65536** [comment]
Update: arm64 builds fine, still need to fix x64 build.

**Comment by Cubik65536** [comment]
There's still issue building for x86_64 on arm64 (Rust is the most apparent one now), and referring to https://chromium.googlesource.com/chromium/src.git/+/master/docs/mac_arm64.md#building-on-arm-macs (and https://issues.chromium.org/issues/40209129), I will disable Intel (x86_64) build for now, until we have a better solution (our own building hosts, or some other patches). This is the best solution I can get, given that I don't have much time to work on this.

/cc @PF4Public @networkException

**Comment by PF4Public** [comment]
> There's still issue building for x86_64 on arm64

I'm just curious why cannot you build not on arm?

**Comment by Cubik65536** [comment]
> > There's still issue building for x86_64 on arm64
> 
> I'm just curious why cannot you build not on arm?

I do not have a machine on Intel, and GitHub Action do not have Intel hosts with newer macOS.

> I'm also hesitant about `or for me to cover some of my personal expenses`. @networkException would this be a good wording?

I also am thinking about that, I might remove it, it was there for transparency at first.

**Comment by Cubik65536** [comment]
> > basically making it impossible to build with older OS
> 
> You're the maintainer, so it is up to you what is best :)

I will investigate what I can do when I have more time, I just don't have that much time now.

> > I want to tell where those contributions go if not Apple Developer License
> 
> I would suggest thinking of it this way: if it was stated to be used for Apple Certificate at the first place (at the time of donation taking place), it should be used for just that. Changing the donation target afterwards might be a moral problem at the very least.

Yeah, I agree with that, I'll change it.

**Comment by PF4Public** [comment]
You removed "future membership years" too :)

**Comment by Cubik65536** [comment]
> You removed "future membership years" too :)

It was because the list contained the sponsors who's contribution that was not counted towards this year's license fee, now that all contributions is only for Apple License, the list will just be updated based on the year and all contributions from the people on the list will only be for this year's Apple License.

**Comment by Cubik65536** [comment]
> > You removed "future membership years" too :)
> 
> It was because the list contained the sponsors who's contribution that was not counted towards this year's license fee, now that all contributions is only for Apple License, the list will just be updated based on the year and all contributions from the people on the list will only be for this year's Apple License.

More on that, I might have to come up with some other ways to sort this out. My initial idea is just asking for some sponsor, and I'll make sure that no matter what, the current and the next year's Apple License should be secured first, and then I might reallocate these for other purpose. This was because UGC is not the only source of sponsor (even though I absolutely know it made the very most part of it), and I couldn't possibly mark every sponsor as Apple License only...

There was a form asking if the contribution is only for UGC (for the matter of making sure people donating for UGC macOS will help UGC macOS on it's license fee), but only 1 out of all sponsors in #184 submitted it, there are way more than 1 recorded in the list because what I did is basically mark everyone as for UGC.

**Comment by PF4Public** [comment]
>My initial idea is just asking for some sponsor help, […] and then I might reallocate these for other purpose.

In no way I'm saying that you cannot do that. I wanted to convey that it would be the fairest if you would clearly and transparently state your intention first and then act accordingly having the approval of your donors.

**Comment by Cubik65536** [comment]
> > My initial idea is just asking for some sponsor help, […] and then I might reallocate these for other purpose.
> 
> In no way I'm saying that you cannot do that. I wanted to convey that it would be the fairest if you would clearly and transparently state your intention first and then act accordingly having the approval of your donors.

This is the idea when I first started the donation project and still is, and I agree that this is not clearly communicated, and it's me to blame for that. The plan now is that I will make sure all previous contributions is for the Apple Developer License, and then I will make this clear in the both the issue and the related README section so it's acknowledged by all future sponsors. Does this sound like a good plan to deal with this?

**Comment by PF4Public** [comment]
> I will make this clear in the both the issue and the related README section so it's acknowledged by all future sponsors. Does this sound like a good plan to deal with this?

Absolutely!

**Comment by Cubik65536** [comment]
> > I will make this clear in the both the issue and the related README section so it's acknowledged by all future sponsors. Does this sound like a good plan to deal with this?
> 
> Absolutely!

I plan to add this note to #184 and the sponsorship section of the README/Announcement:

> [!NOTE]
> The prioritized usage of the sponsorship I received will always be the coverage/securing the Apple Developer Membership fee of the current and the next membership year. However, please acknowledge that, after the current and the next year's membership fee have been fully covered/secured, the donation I received might be reallocated for other personal purpose.

Does this sound good as a clarification for this? /cc @PF4Public @networkException

**Comment by Cubik65536** [comment]
I added the note above regarding sponsorship to the README, and I'll add it to #184 after this PR is merged, in case we still want to change some detail about it. More importantly, let's publish the 131.0.6778.85 update :)

**Review by networkException — APPROVED** [review]
Thanks!

**Pull request merged**
