### PR TITLE
Update to 74.0.3729.131-1

### PR DESCRIPTION
**Pull request by saltama**
The safe-browsing patch required some fixing in the circular dependency section (i've removed other references to safe-browsing too, these could be redundant), the installer patch is now disabling an "updater" component too and a few other minor modifications.

The note about the unlinking of homebrew's binutils in the readme fixes a confusing linker error.

This PR is not ready yet to be merged since i'm still compiling, i'll update it once i'm done.

### CODE REVIEW

**Comment by saltama** [comment]
Done.

**Comment by saltama** [comment]
Do we still miss something related to validation of patches? I followed the readme but noticed we don't have the `validate_patches.py` script anymore here and running it manually doesn't work with this mac only patch set (or... i tried and failed).

**Comment by Eloston** [comment]
The instructions in ungoogled-chromium's README apply for the ungoogled-chromium repo, not platform repos. I've updated this repo's instructions with some clarifications: ad6c2332f7b7fb2afb72e970753d4aad5e47c7fe

Hope that helps.

**Comment by saltama** [comment]
Refreshed and aligned some debian_buster patches with the one you have on the _debian repo. Even if it was not really needed, keeping the shared patches aligned across repos makes sense.

**Comment by saltama** [comment]
The mojo patch taken from the buster repo breaks the build for [this](https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/debian_buster/debian/patches/fixes/mojo.patch#L101) missing property, fix in progress.

**Comment by saltama** [comment]
Ok, good to go, I simply reverted the mojo.patch to its previous state, now it builds successfully and everything works.
I suppose that patch will break `ungoogled-chromium-debian` too once it's updated to 74.0.3729.131.

**Comment by 23rd** [comment]
Yes, I confirm that after the last commit chromium compiles successfully.

**Pull request merged**
