### PR TITLE
Update to ungoogled-chromium 120.0.6099.71

### PR DESCRIPTION
**Pull request by Cubik65536**
Notes:

- A submodule bump is made.
- A patch refresh is made.
- The flag changes in [[4903785]](https://chromium-review.googlesource.com/c/chromium/src/+/4903785) were reverted.
- Add a nodejs download.
- Upgrade the LLVM toolchain to 17.0.6
- Suppress unknown warnings (borrowed from [ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows/blob/master/patches/ungoogled-chromium/windows/windows-no-unknown-warnings.patch) 🧐)

------

Builds and runs fine locally.

image

> [!NOTE]
> The error is caused by the Chromium update feature that have been blocked.

### CODE REVIEW

**Comment by Cubik65536** [comment]
Current progress update:

- A node dependency is missing for ninja. (Check build CI logs) I did manually put a node in the required directory to bypass the error, more helps are needed.
- Flag changes in [[4903785]](https://chromium-review.googlesource.com/c/chromium/src/+/4903785) needs to be reverted in order to build. Working on a patch.

**Comment by Cubik65536** [comment]
There's warning generated by clang:

```sh
warning: unknown warning option '-Wno-thread-safety-reference-return'; did you mean '-Wno-thread-safety-reference'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-delayed-template-parsing-in-cxx20' [-Wunknown-warning-option]
```

I'm trying to get LLVM updated to see if these issues disappears.

**Review by networkException — APPROVED** [review]

**Comment by PF4Public** [comment]
@networkException Were binaries created for this one or it failed again?

**Comment by networkException** [comment]
hm looks like GitHub just didn't start this one..

**Comment by Cubik65536** [comment]
> hm looks like GitHub just didn't start this one..

ummm

Yeah, one of my commit message have a `[skip ci]` tag that got into the merge commit's message body... It seems that it can be placed anywhere and GitHub will skip the CI process. I will try to avoid using that in the futur then.

**Comment by networkException** [comment]
oh I see, haha :sweat_smile:

**Pull request merged**
