### PR TITLE
Update to v110

### LINKED ISSUE #99: Updating to 110
I've looked at updating these patches to support ```chromium-110.0.5481.177```, and while there aren't too many changes needed, I feel that some of them may warrant discussion.

# 1. Debian Patches

In my opinion, these could all be dropped, save for ```patches/debian_buster/disable/installer.patch```, which could go to the upstream ```ungoogled-chromium``` repo, since there's nothing macOS-specific about it.

The [Debian Chromium repo](https://salsa.debian.org/chromium-team/chromium) no longer ships any of these patches, and while most of them still apply, they seem to have no impact when building with the latest LLVM toolchain. (Discussed in the next section.)

I'm not sure if ```patches/inox-patchset/fix-cfi-failures-with-unbundled-libxml.patch``` is needed either. Replacing all uses of ```XmlFree``` with ```free``` seems a bit odd. I don't have an unbundled libxml to test this with, though.

# 2. Toolchain Requirements

Building with LLVM 15 is currently broken. Either https://github.com/chromium/chromium/commit/cb5ad37 needs to be reverted, or the [odd initialization](https://github.com/chromium/chromium/commit/cb5ad37#diff-4f8bd3e1578fbfe105e2f3c248d35ecad20e3cf2b7a3703047afaf87045ef15dR1385) should be changed to work with LLVM 15.

Alternatively, the minimum LLVM version could be bumped to LLVM 16, though it remains unreleased as of yet. (It's not yet available in homebrew, so maybe the build script could handle building it?) However, building with LLVM 16 is broken on arm without https://github.com/chromium/chromium/commit/9f43d82. (See https://bugs.chromium.org/p/chromium/issues/detail?id=1405048)

I'd prefer requiring LLVM 16 for maximum compatibility, but supporting older releases shouldn't be too difficult (yet.)

### PR DESCRIPTION
**Pull request by implicitfield**
Closes #99.

Highlights:
- Removed all of the ```debian_buster``` and ```inox``` patches. (Please leave comment if your setup depends on any of them.)
- Updated google-toolbox-for-mac and LLVM.
- Added a patch to fix building with LLVM 15.
- Added a patch to disable the clang version check. (Copied verbatim from the [Windows port](https://github.com/ungoogled-software/ungoogled-chromium-windows/blob/master/patches/ungoogled-chromium/windows/windows-disable-clang-version-check.patch). Maybe this patch should be in the upstream repo?)
- Added another patch to allow bootstrapping ```gn``` with the default Python path.
- Removed instructions relating to Python 2 from the readme, as it seems that it's not needed anymore.
- Updated the copyright year.

~~I haven't tested packaging this yet, and someone else should probably test this out with their own setup as well, but otherwise I consider this ready for review.~~
UPDATE: Verified that this PR can build a functional DMG with ```build.sh```.

### CODE REVIEW

**Comment by PF4Public** [comment]
Please address the failing test.

**Comment by PF4Public** [comment]
It seems to be building just fine. @networkException what do you think?

**Comment by networkException** [comment]
LGTM! I'm not familiar with the CI setup here but I assume merging and tagging should create a release? Also we need to figure out how to point homebrew at this repository

**Review by PF4Public — APPROVED** [review]

**Review by networkException — APPROVED** [review]

**Comment by PF4Public** [comment]
I've canceled all workflows except the tag-related.

**Comment by PF4Public** [comment]
> Also we need to figure out how to point homebrew at this repository

It seems to be pointing to kramred's repository [since like eternity](https://github.com/Homebrew/homebrew-cask/commit/d95dc496e943e104a1016f14538fe0cd25a56ef3) :)

**Comment by networkException** [comment]
@kramred I only just now saw that you also published a release for this version on your fork. Are you still keeping that fork alive?

I'd generally like to have canonical packaging in this repository, as, if I understood you correctly, you don't have enough time to maintain packaging consistently. Ideally other people could just step in and push updates here.

**Comment by ansoni-san** [comment]
kamred’s fork has been the only place producing fairly up-to-date arm64 builds for a long time.

The cost of macOS ARM64 workflows on github actions is incredibly high from what I remember.

**Comment by kramred** [comment]
Hi,

thank you all, esp. @implicitfield, for keeping the macOS version up to date and having the binary releases here in the official macOS repo now.
I had pushed a release for the v110 version in my repo to have the updated binary available via homebrew.

The [cask code](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/eloston-chromium.rb) for homebrew needs an update to point here and all should be good again regarding installing/updating via brew.

**Comment by networkException** [comment]
Alright, thanks for the update. I'm currently a bit busy, @implicitfield would you be willing to maintain this repo more actively (thats mainly publishing releases and getting them onto homebrew, etc)?

**Pull request merged**
