### PR TITLE
Update to ungoogled-chromium 123.0.6312.122

### PR DESCRIPTION
**Pull request by Cubik65536**
No modification aside from the submodule bump is needed.

---

Builds and runs fine locally.

image

### CODE REVIEW

**Comment by PF4Public** [comment]
Is Cirrus gonna run any time soon? :D

**Comment by networkException** [comment]
in doubt doesn't matter

**Review by networkException — APPROVED** [review]

**Comment by Cubik65536** [comment]
> Is Cirrus gonna run any time soon? :D

From what I can tell, no :(

I am working on CI migration though.

**Comment by Cubik65536** [comment]
Update:

Ninja is not very happy on x86_64, working on a fix.

**Comment by Cubik65536** [comment]
Update, again:

Chromium has a ninja flag that is no longer available since an update of Ninja, arm64 wasn't impacted because brew didn't update it...

**Comment by Cubik65536** [comment]
Should I try to remove that flag or try to use Ninja installed from other sources? /cc @PF4Public @networkException

**Comment by networkException** [comment]
Well unless chromium requires to use a custom (/ outdated) version of ninja for builds we would have to remove the flag anyways going forward

**Comment by Cubik65536** [comment]
> Well unless chromium requires to use a custom (/ outdated) version of ninja for builds we would have to remove the flag anyways going forward

#162 up for fix this, I just removed the flag, not sure what Chromium will do for now.

**Pull request merged**
