### PR TITLE
Testing CI

### PR DESCRIPTION
**Pull request by saltama**

### CODE REVIEW

**Comment by saltama** [comment]
Ok! CI started as expected.

**Comment by saltama** [comment]
Build completed in 2:30.

**Comment by Eloston** [comment]
Awesome! That's a pretty fast build for a free CI service.

**Comment by kramred** [comment]
The macOS resources seem to be a bit beefier than the ones stated in [Github actions: HW resources](https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources) – that might explain the rather quick build time.
I ran `system_profiler -timeout 30 -detailLevel basic` in a GitHub Action for macOS and got

```
Hardware:

    Hardware Overview:

      Model Name: Apple device
      Model Identifier: VMware7,1
      Processor Speed: 3.33 GHz
      Number of Processors: 4
      Total Number of Cores: 4
      L2 Cache (per Processor): 256 KB
      L3 Cache (per Processor): 12 MB
      Memory: 12 GB
…
```

**Pull request closed without merging**
