### PR TITLE
Update to ungoogled-chromium 128.0.6613.113

### PR DESCRIPTION
**Pull request by Cubik65536**
No modification aside from the submodule bump is needed.

---

Builds and runs fine locally.

CleanShot 2024-08-30 at 00 57 01

---

Signed-off-by: Qian Qian "Cubik"‎ <cubik65536@cubik65536.top>

### CODE REVIEW

**Review by PF4Public — APPROVED** [review]

**Comment by Cubik65536** [comment]
The blog post says:

> The Stable channel has been updated to 128.0.6613.113/.114 for Windows, Mac

stating that 128.0.6613.113 and .114 are identical for Windows and macOS except the version number. You can verify it by checking their [git log](https://chromium.googlesource.com/chromium/src/+log/128.0.6613.113..128.0.6613.114?pretty=fuller&n=10000), which will show that the different is just a version number bump.

The GitHub Action notification will only get the latest version number, that I will not use. I will follow the [ungoogled-chromium core](https://github.com/ungoogled-software/ungoogled-chromium/) version number, not just the most up-to-date Chromium one for consistency.

**Comment by Cubik65536** [comment]
It seems that all build actions failed due to the GitHub Action host issue...

**Comment by PF4Public** [comment]
I think, you'll have to either clean space on a runner or do the selective extraction, or both.

**Comment by Cubik65536** [comment]
> I think, you'll have to either clean space on a runner or do the selective extraction, or both.

To be honest I don’t think the UGC resource are large enough to fill all the space (unless GitHub reduced it again), and I am trying to investigate on what can I remove to clean more disk space.

**Comment by Cubik65536** [comment]
I am going to rerun the action once more. If it still doesn't work, I will probably release this version manually.

**Comment by Cubik65536** [comment]
No luck, I am starting to build locally.

**Comment by Cubik65536** [comment]
> > I am going to rerun the action once more. If it still doesn't work, I will probably release this version manually.
> 
> Thanks but, manually as in, how? We still want to see the source code, 2 approvals from other project members, diff with changes, etc. And that the release will be formed from this branch, not from a 3d party one. This is not too much to ask, especially after the XZ story earlier this year. Just basic requirements. You can probably clean up the worker spaces and not build them both (x86_64 and arm64) simultaneously, definitely it's possible to use a GH space for each build separately.

They are used separately already, and it is not even enough for any host to complete even one build. And I don't have any information on what can be cleaned from the action host and what not.

Manually, as in creating a release that maybe doesn't even contain a built binary because I don't even know if I can build an x86_64 version out. Users, whether they want it or not, may **have** to build this version on their own.

The source code is here, it is approved. I am not going to release anything that differs from what is currently in the master branch. Even if I will provide built binaries, I will also provide ways for users to verify what I release, which may be just "build one yourself and check it". And I can only hope that there are enough people who know how to build this to verify it and gives it a thumbs up so others who don't know or want to build it themselves to say that it is at least somewhat safe to use.

**Comment by Cubik65536** [comment]
An update:

The log of arm64 builds would show:

```
+ sudo df -h
Filesystem        Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk3s1s1   295Gi   9.6Gi    19Gi    34%    404k  201M    0%   /
```

where as previous ones normally shows:

```
+ sudo df -h
Filesystem        Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk3s1s1   295Gi   9.6Gi    58Gi    15%    404k  607M    0%   /
```

meaning that there is a decrease of available space provided by these hosts. However, it seems that `macos-13` hosts are not impacted, so I am currently switching to `macos-13` for both x86_64 and arm64 builds, which would, hopefully, solve the problem. At least for now.

**Pull request merged**
