### PR TITLE
Update to ungoogled-chromium 126.0.6478.61

### PR DESCRIPTION
**Pull request by Cubik65536**
Notes:

- A submodule bump is made.
- A patch refresh is made.
- Rust is updated according to Chromium requirement.
- LLVM is updated from 18.1.1 to 18.1.7
- ThinLTO is disabled to solve `__rust_alloc` issue described in https://github.com/ungoogled-software/ungoogled-chromium/pull/2902#issuecomment-2161983232

---

Builds and runs fine locally.

image

---

Signed-off-by: Qian Qian "Cubik"‎ <cubik65536@cubik65536.top>

### CODE REVIEW

**Comment by tsuliwaensis** [comment]
I get the error `ERROR: File checksum does not match: /ungoogled-chromium-macos/build/download_cache/clang+llvm-18.1.7-x86-64-apple-darwin21.0.tar.xz` when building

**Comment by Cubik65536** [comment]
> I get the error `ERROR: File checksum does not match: /ungoogled-chromium-macos/build/download_cache/clang+llvm-18.1.7-x86-64-apple-darwin21.0.tar.xz` when building

I'll take a look right now.

**Comment by Cubik65536** [comment]
> I get the error `ERROR: File checksum does not match: /ungoogled-chromium-macos/build/download_cache/clang+llvm-18.1.7-x86-64-apple-darwin21.0.tar.xz` when building

Should be fixed.

**Comment by PF4Public** [comment]
> * ThinLTO is disabled to solve `__rust_alloc` issue described

Haven't you conquered the problem yet? It it ready to merge as is?

**Comment by Cubik65536** [comment]
> > * ThinLTO is disabled to solve `__rust_alloc` issue described
> 
> Haven't you conquered the problem yet? It it ready to merge as is?

The problem is conquered. (PR is ready to be merged.)

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
