### PR TITLE
Update to ungoogled-chromium 120.0.6099.129

### PR DESCRIPTION
**Pull request by Cubik65536**
No modification aside from the submodule bump is needed.

------

Builds and runs fine locally.

image

### CODE REVIEW

**Review by PF4Public — APPROVED** [review]

**Comment by Cubik65536** [comment]
Is there anything that's holding this PR back? /cc @PF4Public

**Comment by PF4Public** [comment]
Sorry @Cubik65536 Busy times :)

**Comment by networkException** [comment]
aw damn, totally didn't have this on my radar anymore

**Comment by Cubik65536** [comment]
> aw damn, totally didn't have this on my radar anymore

Maybe we can have an auto PR reviewer request or something similar for notifications?

**Comment by networkException** [comment]
I am subscribed on the whole organization, that with other open source projects (mostly specific issues / prs on those cases) I work on or am subscribed to amounts to quite a lot of emails that I'm currently a bit behind on. (2.6k since 2023-11-01 in total)

**Comment by AlaisterLeung** [comment]
It seems the build is failing

https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/7361151009/job/20038154725

`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?`

**Comment by PF4Public** [comment]
> bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

@Cubik65536  Wasn't this failure fixed recently?

**Comment by Cubik65536** [comment]
> > bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
> 
> @Cubik65536 Wasn't this failure fixed recently?

It was.

The issue was fixed by reverting Python for our CI to 3.11, not sure if that got bumped up in some way to 3.12 again and caused the issue, maybe we can still try to revert it in some way.

I'm off for now and I'll (re)investigate on this probably 1 or 2 days later.

**Comment by Cubik65536** [comment]
Just a quick update, I'm a bit busy these days and I will try to put up a fix by this weekend.

**Comment by PF4Public** [comment]
> Just a quick update, I'm a bit busy these days and I will try to put up a fix by this weekend.

No worries, take your time, it is a volunteer work after all.

**Comment by Cubik65536** [comment]
> It seems the build is failing
> 
> [ungoogled-software/ungoogled-chromium-macos/actions/runs/7361151009/job/20038154725](https://github.com/ungoogled-software/ungoogled-chromium-macos/actions/runs/7361151009/job/20038154725)
> 
> `bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?`

#139 is up for a fix

**Pull request merged**
