### PR TITLE
Update to ungoogled-chromium 115.0.5790.114 + CI Maintenance

### PR DESCRIPTION
**Pull request by implicitfield**
No changes to the patches were needed. While #117 fixed the x86_64 build, the arm build faced issues due to `hdiutil` timing out. Syncing before running that command should fix it. `continue-on-error` has also been disabled to get rid of pointless CI runs and to better inform us when a build fails.

### CODE REVIEW

**Comment by PF4Public** [comment]
>Syncing before running that command should fix it.

Sorry, but syncing what?

**Comment by arjpar** [comment]
Is this PR the reason why v115 hasn't been released for arm64?

**Comment by arjpar** [comment]
@PF4Public or @networkException: could you review this PR when/if you get the time?

**Review by PF4Public — APPROVED** [review]
👍🏻

**Pull request merged**
