### PR TITLE
Update to ungoogled-chromium 130.0.6723.58

### PR DESCRIPTION
**Pull request by Cubik65536**
This Pull Request updates the package to ungoogled-chromium 130.0.6723.58, and changes CI workflow to publish **Apple Developer Notarized Build**.

Notes:
- A submodule bump is made.
- A patch refresh is made.
- Rust is updated according to Chromium requirement.
- The GitHub Action workflow is changed so new binaries released will be signed by Apple Developer Account (Authority `Developer ID Application: Qian Qian (B9A88FL5XJ)`, `Developer ID Certification Authority`, `Apple Root CA`).

---

Builds and runs fine.

CleanShot 2024-10-22 at 01 17 49

CleanShot 2024-10-22 at 01 18 30

---

Signed-off-by: Qian Qian "Cubik"‎ <cubik65536@cubik65536.top>

### CODE REVIEW

**Comment by Cubik65536** [comment]
The application notarization script is being tested.

First Try (running): https://github.com/iXORTech/ungoogled-chromium-macos/actions/runs/11355758475

**Comment by Cubik65536** [comment]
Could you explain the 

```bash
codesign --sign "$MACOS_CERTIFICATE_NAME" --force --timestamp --identifier io.dekker.ungoogled-chromium --options restrict,library,runtime,kill --entitlements ./entitlements/app-entitlements.plist --requirements '=designated => identifier "io.dekker.ungoogled-chromium" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */' /Applications/Chromium.app
```

part of your script? I'm not very familiar with this part of the codesign process and is a bit confused by the parameters following `--requirements`.

**Comment by Cubik65536** [comment]
> Could you explain the
> 
> ```shell
> codesign --sign "$MACOS_CERTIFICATE_NAME" --force --timestamp --identifier io.dekker.ungoogled-chromium --options restrict,library,runtime,kill --entitlements ./entitlements/app-entitlements.plist --requirements '=designated => identifier "io.dekker.ungoogled-chromium" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */' /Applications/Chromium.app
> ```
> 
> part of your script? I'm not very familiar with this part of the codesign process and is a bit confused by the parameters following `--requirements`.

/cc @claudiodekker

**Comment by PF4Public** [comment]
So did it work in the end?

**Comment by Cubik65536** [comment]
> So did it work in the end?

I am testing locally now, it seems working.

**Comment by Cubik65536** [comment]
By the way I need access to settings to this repository for setting up secrets for signing, could you give me permissions to do so? /cc @PF4Public @networkException

**Comment by Cubik65536** [comment]
The past **few** action runs actually failed, despite action shows it's successful. The GitHub action `env` are not properly set, so the signing script actually failed. I am still trying to solve the issue.

/cc @claudiodekker

Do you have any idea what might be happening as my action running log shows

```
  env:
    MACOS_CERTIFICATE: 
    MACOS_CERTIFICATE_PWD: 
    MACOS_CERTIFICATE_NAME: 
    MACOS_CI_KEYCHAIN_PWD: 
    PROD_MACOS_NOTARIZATION_APPLE_ID: 
    PROD_MACOS_NOTARIZATION_TEAM_ID: 
    PROD_MACOS_NOTARIZATION_PWD: 
```

showing it's all empty instead of having `***` that suggests that secrets are redacted?

**Comment by Cubik65536** [comment]
> The past **few** action runs actually failed, despite action shows it's successful. The GitHub action `env` are not properly set, so the signing script actually failed. I am still trying to solve the issue.
> 
> /cc @claudiodekker
> 
> Do you have any idea what might be happening as my action running log shows
> 
> ```
>   env:
>     MACOS_CERTIFICATE: 
>     MACOS_CERTIFICATE_PWD: 
>     MACOS_CERTIFICATE_NAME: 
>     MACOS_CI_KEYCHAIN_PWD: 
>     PROD_MACOS_NOTARIZATION_APPLE_ID: 
>     PROD_MACOS_NOTARIZATION_TEAM_ID: 
>     PROD_MACOS_NOTARIZATION_PWD: 
> ```
> 
> showing it's all empty instead of having `***` that suggests that secrets are redacted?

OK now it is working, confusing GitHub Action setup stuff 💀

**Comment by Cubik65536** [comment]
The newest running action https://github.com/iXORTech/ungoogled-chromium-macos/actions/runs/11427055702/job/31800212783 seems to be working, however, the Notarization process by `xcrun notarytool submit notarize.zip --keychain-profile notarytool-profile --wait` command seems to be stuck in "In Progress" like I experience on local environment.

/cc @claudiodekker Could you maybe provide some help on this? Is this normal?

**Comment by Cubik65536** [comment]
OK the notarization just take extremely long time for us (my terminated request from 2 days ago is not shown as accepted in history record)...

**Comment by Cubik65536** [comment]
Yes, it is way faster once we have the app being accepted once (see https://github.com/iXORTech/ungoogled-chromium-macos/actions/runs/11427055702 rerun no.2, it only has arm64 build notarized though). I think this is almost ready to be merged and released.

Just before that, I will update the announcement, and I'll need settings permission to this repo to set up notarization secrets. @PF4Public @networkException can you give me the access to this repo's admin permission?

**Comment by networkException** [comment]
Sorry for the delay, you can change the secrets now. If you don't need admin for anything else I'd remove it in the interest of least privilege again after :)

**Comment by Cubik65536** [comment]
@networkException It's all set now, I'll commit the new announcement soon and then this will be good to go!

**Comment by Cubik65536** [comment]
I think it's good to go!

**Comment by Cubik65536** [comment]
Is there anything blocking this PR?

I think, as .6723.69 tarball is still not yet released so the new version can't be built here yet, we should merge this one first? /cc @networkException @PF4Public

**Comment by PF4Public** [comment]
Are organisational things settled down?

**Comment by Cubik65536** [comment]
> Are organisational things settled down?

I think my admin privileges are yet to be removed, otherwise everything are set.

**Comment by PF4Public** [comment]
> I think my admin privileges are yet to be removed

@networkException

**Comment by networkException** [comment]
Already did

**Review by networkException — APPROVED** [review]

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
