### PR TITLE
Update to Ungoogled-Chromium 124.0.6367.91

### PR DESCRIPTION
**Pull request by Cubik65536**
Notes:

- A submodule bump is made.
- Rust is updated according to Chromium requirement.
- A patch refresh is made.
- Cirrus CI related files are **removed**. Migration to GitHub Action is still in progress.
- Ninja 1.11.1 is now **forced** during build CI.
- A symlink from `llvm-install-name-tool` to `install_name_tool` is created.
	- `install_name_tool` is used by Vanilla Chromium, however, it is a part of Apple Clang toolkit and not a part of LLVM. `llvm-install-name-tool` is the drop-in replacement for it inside LLVM, and the symlink is created so it can be used when building.

---

Builds and runs fine locally.

image

---

Signed-off-by: Qian Qian "Cubik"‎ <cubik65536@cubik65536.top>

### CODE REVIEW

**Comment by Cubik65536** [comment]
It seems that Ninja 1.12.0 causes lots more problems... I will just use a reverted version then.

**Comment by Cubik65536** [comment]
I am updating to 124.0.6367.78.

**Comment by Cubik65536** [comment]
It's now updated:

image

Please review @networkException

**Comment by networkException** [comment]
I think you forgot to push the bump to .78

Otherwise LGTM, the next bump will follow in a bit as well

**Comment by Cubik65536** [comment]
> I think you forgot to push the bump to .78

Sorry, I forgot to push :(

> Otherwise LGTM, the next bump will follow in a bit as well

If that's the case, maybe I'd wait till the next update (if it comes in just 1~2 days).

**Comment by Cubik65536** [comment]
It is now updated to version 124.0.6367.91 and should be good to go.

image

/cc @networkException

**Review by networkException — APPROVED** [review]
yep thanks a lot!

**Pull request merged**
