### PR TITLE
Update to ungoogled-chromium 120.0.6099.216

### PR DESCRIPTION
**Pull request by Cubik65536**
No modification aside from the submodule bump is needed.

------

Builds and runs fine locally.

image

### CODE REVIEW

**Comment by PF4Public** [comment]
Thanks @Cubik65536 

Perhaps we should implement auto-tagging somehow, @networkException ?

**Comment by networkException** [comment]
my plan was to reduce the tags to one (not per architecture anymore) and find a maintainer

**Comment by Cubik65536** [comment]
> my plan was to reduce the tags to one (not per architecture anymore) and find a maintainer

I can help to develop the action script if needed and I'm interested in being a maintainer for the project 😃

**Comment by Cubik65536** [comment]
`html5lib` error is back again... 🤯
I'll try to put up another fix.

**Pull request merged**
