### PR TITLE
Update to ungoogled-chromium 123.0.6312.86

### LINKED ISSUE #151: Use arm64 LLVM when building UGC on Apple Silicon
(This can still be viewed as a part of the works to improve compiling efficiency)

As for now, even if we build ungoogled-chromium-macos on Apple Silicon (arm64), an x86-64 version of LLVM is still used to compile. I think we should try to use arm64 LLVM in this case instead, so no translation for binaries are needed.

This might consist of appending different entries to `downloads.ini` while running build script.

Any opinions on this? /cc @networkException @PF4Public

### PR DESCRIPTION
**Pull request by Cubik65536**
Notes:

- (continuation of #156)
- LLVM is updated to 18. (continuation of #155)
	- closes #151 (P.S.: The use of ARM64 LLVM improved build time on local environment by a lot.)
	- LLVM 17 related patches is removed.
- A submodule bump is made.
- A patch refresh is made.
- Rust disable patches are removed.
- Rust toolchain download and unpack are added.
- Rust is enabled.
- `disable-missing-clang-flags` patch is removed.
- Documentations related to ungoogled-chromium update is updated.

---

Builds and runs fine locally

image

### CODE REVIEW

**Comment by Cubik65536** [comment]
Some issues were found with the GitHub CI building... I will try to get it fixed by this weekend.

**Comment by Cubik65536** [comment]
[Everything now builds and runs](https://github.com/iXORTech/ungoogled-chromium-macos/actions/runs/8476361569). Should be good to go.
/cc @networkException @PF4Public

**Review by networkException — APPROVED** [review]
Lets get this merged then :)

**Comment by Cubik65536** [comment]
By the way, it seems that the source check on Cirrus are always scheduled but not running...

**Comment by networkException** [comment]
hm yes, for the binaries repository we also moved to GitHub Actions for these kinda things. Feel free to remove the check entirely for now though if you're not interested in working on a migration.

**Comment by Cubik65536** [comment]
> hm yes, for the binaries repository we also moved to GitHub Actions for these kinda things. Feel free to remove the check entirely for now though if you're not interested in working on a migration.

Okay I see, I will then try to migrate the check to GitHub Actions then. Thanks for the update.

**Pull request merged**
